//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SN_Net.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class note_istab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public note_istab()
        {
            this.event_calendar = new HashSet<event_calendar>();
        }
    
        public int id { get; set; }
        public string tabtyp { get; set; }
        public string typcod { get; set; }
        public string abbreviate_en { get; set; }
        public string abbreviate_th { get; set; }
        public string typdes_en { get; set; }
        public string typdes_th { get; set; }
        public bool use_pattern { get; set; }
        public string creby { get; set; }
        public System.DateTime credat { get; set; }
        public string chgby { get; set; }
        public Nullable<System.DateTime> chgdat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<event_calendar> event_calendar { get; set; }
    }
}
