//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SN_Net.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sn_noteEntities : DbContext
    {
        public sn_noteEntities()
            : base("name=sn_noteEntities")
        {
        }
    
        public sn_noteEntities(string connection_string)
            : base(connection_string)
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<note> note { get; set; }
        public virtual DbSet<note_comment> note_comment { get; set; }
    }
}
